version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.6.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  calculator-core:
    build:
      context: .
      dockerfile: calculator-core/Dockerfile
    depends_on:
      - kafka
      - zookeeper
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  calculator-rest:
    build:
      context: .
      dockerfile: calculator-rest/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - calculator-core
      - kafka
      - zookeeper
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
